app:
  image: unocha/alpine-base-nginx
  environment:
    DNSDOCK_NAME: app
    DNSDOCK_IMAGE: hid
  ports:
    - 80:80
  volumes:
    - ./src:/srv/www/html
    - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
  hostname: app.hid.vm
