app:
  image: unocha/alpine-base-nginx
  volumes:
    - ./dist:/srv/www/html
    - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
    - ./conf/nginx/ssl:/etc/nginx/ssl
#  hostname: app.hid.vm
  ports:
    - 443:443
