#!/bin/bash -xe

echo "Starting prebuild..."

# make sure we got the latest builder
docker pull unocha/alpine-nodejs-builder

# build it
docker run --privileged --rm \
    -v $(pwd):/src \
    -v /var/run/docker.sock:/var/run/docker.sock \
    unocha/alpine-nodejs-builder \
    sh -c "npm install && \
        cd /src && bower --allow-root install && \
        grunt --target=dev && \
        ls -l /src && \
        mv /src/src/dist /src/html"

echo "Prebuild complete."
