#!/bin/bash

echo "Starting prebuild..."

# make sure we got the latest builder
docker pull unocha/alpine-nodejs-builder

# build it
docker run --privileged --rm \
    -v $(pwd):/src \
    -v /var/run/docker.sock:/var/run/docker.sock \
    unocha/alpine-nodejs-builder \
    sh -c "cd /src && \
        yarn --ignore-engines && \
        grunt --target=production && \
        mv /src/dist /src/html"

echo "Prebuild complete."
